# Generated by Django 4.1.5 on 2023-03-25 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='box',
        ),
    ]
