# Generated by Django 4.1.5 on 2023-03-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='toemail',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
